"""add score breakdown columns to hotspot_scores

Revision ID: 1b3ed4d60767
Revises: 4d6b7f874b16
Create Date: 2026-09-29 22:15:46.548197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3ed4d60767'
down_revision: Union[str, Sequence[str], None] = '4d6b7f874b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot_scores', sa.Column('complaint_rate_per_100k', sa.Numeric(), nullable=True))
    op.add_column('hotspot_scores', sa.Column('infra_gap', sa.Numeric(), nullable=True))
    op.add_column('hotspot_scores', sa.Column('current_population_estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspot_scores', 'current_population_estimate')
    op.drop_column('hotspot_scores', 'infra_gap')
    op.drop_column('hotspot_scores', 'complaint_rate_per_100k')
    # ### end Alembic commands ###
