"""add claimed_at fr accurate stuck-row detection

Revision ID: 202733177ea6
Revises: 1b3ed4d60767
Create Date: 2026-09-30 00:22:27.576669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202733177ea6'
down_revision: Union[str, Sequence[str], None] = '1b3ed4d60767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'claimed_at')
    # ### end Alembic commands ###
