"""add  attempts and error_reason to feedback

Revision ID: 4d6b7f874b16
Revises: e17e98bf745d
Create Date: 2026-09-29 00:41:46.430679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6b7f874b16'
down_revision: Union[str, Sequence[str], None] = 'e17e98bf745d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('feedback', sa.Column('error_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'error_reason')
    op.drop_column('feedback', 'attempts')
    # ### end Alembic commands ###
