"""add distinct_issue_count to hotspot_scores

Revision ID: 525d8e36e00f
Revises: 9e0901633da2
Create Date: 2026-09-30 18:42:20.822412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525d8e36e00f'
down_revision: Union[str, Sequence[str], None] = '9e0901633da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot_scores', sa.Column('distinct_issue_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspot_scores', 'distinct_issue_count')
    # ### end Alembic commands ###
