"""initial schema: feedback, district__indicators, hotspot_score

Revision ID: 58a8b048eaf1
Revises: 
Create Date: 2026-09-06 15:55:12.831693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a8b048eaf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_indicators',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('infra_index', sa.Numeric(), nullable=True),
    sa.Column('literacy_rate', sa.Numeric(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('district')
    )
    op.create_table('hotspot_scores',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=True),
    sa.Column('dominant_topic', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Numeric(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['district_indicators.district'], ),
    sa.PrimaryKeyConstraint('district')
    )
    op.create_unique_constraint('uq_feedback_dedup', 'feedback', ['raw_input', 'source_channel', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_feedback_dedup', 'feedback', type_='unique')
    op.drop_table('hotspot_scores')
    op.drop_table('district_indicators')
    # ### end Alembic commands ###
