"""add internet_access_rate to district_indicators

Revision ID: 75baf73e0a52
Revises: 202733177ea6
Create Date: 2026-09-30 17:00:30.502383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75baf73e0a52'
down_revision: Union[str, Sequence[str], None] = '202733177ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('district_indicators', sa.Column('internet_access_rate', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('district_indicators', 'internet_access_rate')
    # ### end Alembic commands ###
