"""add underreporting_multiplier to hotspot_scores

Revision ID: 9e0901633da2
Revises: 75baf73e0a52
Create Date: 2026-09-30 17:04:32.333302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0901633da2'
down_revision: Union[str, Sequence[str], None] = '75baf73e0a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspot_scores', sa.Column('underreporting_multiplier', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotspot_scores', 'underreporting_multiplier')
    # ### end Alembic commands ###
