"""uuid ids, client_reference_id, status rename

Revision ID: e17e98bf745d
Revises: 58a8b048eaf1
Create Date: 2026-09-10 11:36:04.121970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17e98bf745d'
down_revision: Union[str, Sequence[str], None] = '58a8b048eaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_indicators',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('infra_index', sa.Numeric(), nullable=True),
    sa.Column('literacy_rate', sa.Numeric(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('district')
    )
    op.create_table('hotspot_scores',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=True),
    sa.Column('dominant_topic', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Numeric(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['district_indicators.district'], ),
    sa.PrimaryKeyConstraint('district')
    )
    op.add_column('feedback', sa.Column('client_reference_id', sa.String(), nullable=True))
    op.execute('ALTER TABLE feedback ALTER COLUMN id DROP DEFAULT')
    op.alter_column('feedback', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.execute('ALTER TABLE feedback ALTER COLUMN id SET DEFAULT gen_random_uuid()')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('feedback', 'client_reference_id')
    op.drop_table('hotspot_scores')
    op.drop_table('district_indicators')
    # ### end Alembic commands ###
